import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outDir = resolve(__dirname, 'vault/.obsidian/plugins/link-dict');
const outfile = resolve(outDir, 'main.js');

if (!existsSync(outDir)) {
	mkdirSync(outDir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	minify: prod,
});

function copyRuntimeFiles() {
	copyFileSync(resolve(__dirname, 'manifest.json'), resolve(outDir, 'manifest.json'));
	copyFileSync(resolve(__dirname, 'styles.css'), resolve(outDir, 'styles.css'));
	console.log(`Copied manifest.json and styles.css to ${outDir}`);
}

if (prod) {
	await context.rebuild();
	copyRuntimeFiles();
	console.log(`Build complete: ${outfile}`);
	process.exit(0);
} else {
	copyRuntimeFiles();
	console.log(`Watching for changes... Output: ${outDir}`);
	await context.watch();
}